Add DB migration for oauth2_unvalidated_credentials table
hypothesis/lti pull request #69
Opened 2017-08-16 15:33 UTC by seanh

2017-08-16 16:16 UTC, seanh commented on conf/alembic.ini
> +sqlalchemy.url: postgresql://postgres@localhost:5433/postgres
This is the default location for the DB in a dev env, it's overwritten by the `DATABASE_URL` env var in `env.py` below.

2017-08-16 16:16 UTC, seanh commented on lti/migrations/env.py
> +    return config.get_main_option("sqlalchemy.url")
This is copied from h

2017-08-16 16:16 UTC, seanh commented on lti/migrations/env.py
> +    url = get_database_url()
`get_database_url()` is used here, same as in h

2017-08-16 16:17 UTC, seanh commented on lti/migrations/env.py
> +    config.set_section_option(section, 'sqlalchemy.url', get_database_url())
Again stuff copied from h to get it to use `get_database_url()` / the `DATABASE_URL` env var

2017-08-16 16:18 UTC, seanh commented on conf/alembic.ini
> +sqlalchemy.url: postgresql://postgres@localhost:5433/postgres
Apart from editing the `sqlalchemy.url` setting by the way, and deleting some comments, this `alembic.ini` file is as generated by `alembic init`

2017-08-16 16:19 UTC, seanh commented on conf/production.ini
> +qualname = alembic
h had this alembic logging stuff in `app.ini` so I copied it

2017-08-16 16:19 UTC, seanh commented on lti/migrations/script.py.mako
> +    ${downgrades if downgrades else "pass"}
This template is the same as `alembic init` generates, same as h's

2017-08-16 16:26 UTC, seanh commented on lti/migrations/env.py
> +    return config.get_main_option("sqlalchemy.url")
This is copied from h except that it just returns `os.environ['DATABASE_URL']` directly, it doesn't have a `database_url()` function to pass it through like h does. Which is maybe not ideal but would have to tweak how the config functions work. This should be fine

2017-08-16 16:26 UTC, seanh commented
I've tested that this works, upgrading and downgrading, locally. Also tested that I can break the sqlalchemy URL in alembic.ini and then fix it by setting `DATABASE_URL` in the env, so I think the env var does work for migrations.

2017-08-17 09:18 UTC, chdorner requested changes
Looks great :+1:

I think the default port in the alembic config is wrong, but otherwise all good.

2017-08-17 09:18 UTC, chdorner commented on conf/alembic.ini
> +sqlalchemy.url: postgresql://postgres@localhost:5435/postgres
I think the port should be `5433`, right?

2017-08-17 09:36 UTC, seanh commented
Fixed and merged, thanks!

2017-08-17 09:36 UTC, merged